#Regi�o geogr�fica intermediaria

regioes = {
	"JOAO PESSOA" : [
		"ALHANDRA", "BAYEUX", "CAAPORA", "CABEDELO", "CALDAS BRANDAO", "CONDE", "CRUZ DO ESPIRITO SANTO", "CUITE DE MAMANGUAPE", "GURINHEM", "JOAO PESSOA", "JUAREZ TAVORA", "JURIPIRANGA", "LUCENA", "MARI", "PEDRAS DE FOGO", "PILAR", "PITIMBU", "RIACHAO DO POCO", "SANTA RITA", "SAO MIGUEL DE TAIPU", "SAPE", "SOBRADO",
        "ALAGOINHA", "ARACAGI", "ARARA", "ARARUNA", "BANANEIRAS", "BELEM", "BORBOREMA", "CACIMBA DE DENTRO", "CAICARA", "CASSERENGUE", "CUITEGI", "DONA INES", "DUAS ESTRADAS", "GUARABIRA", "LAGOA DE DENTRO", "LOGRADOURO", "MULUNGU", "PILOES", "PILOEZINHOS", "PIRPIRITUBA", "RIACHAO", "SERRA DA RAIZ", "SERRARIA", "SERTAOZINHO", "SOLANEA", "TACIMA",
        "BAIA DA TRAICAO", "CAPIM", "CURRAL DE CIMA", "ITAPOROROCA", "JACARAU", "MAMANGUAPE", "MARCACAO", "MATARACA", "PEDRO REGIS", "RIO TINTO",
        "ITABAIANA", "MOGEIRO", "NATUBA", "SALGADO DE SAO FELIX", "SAO JOSE DOS RAMOS"],
	"CAMPINA GRANDE" : [
        "ALAGOA GRANDE", "ALAGOA NOVA", "ALCANTIL", "ALGODAO DE JANDAIRA", "AREIA", "AREIAL", "AROEIRAS", "ASSUNCAO", "BARRA DE SANTANA", "BARRA DE SAO MIGUEL", "BOA VISTA", "BOQUEIRAO", "CABACEIRAS", "CAMPINA GRANDE", "CARAUBAS", "CATURITE", "CUBATI", "ESPERANCA", "FAGUNDES", "GADO BRAVO", "GURJAO", "INGA", "ITATUBA", "JUAZEIRINHO", "JUNCO DO SERIDO", "LAGOA SECA", "MASSARANDUBA", "MATINHAS", "MONTADAS", "OLIVEDOS", "POCINHOS", "PUXINANA", "QUEIMADAS", "REMIGIO", "RIACHAO DO BACAMARTE", "RIACHO DE SANTO ANTONIO", "SANTA CECILIA", "SANTO ANDRE", "SAO DOMINGOS DO CARIRI", "SAO JOAO DO CARIRI", "SAO SEBASTIAO DE LAGOA DE ROCA", "SAO VICENTE DO SERIDO", "SERRA REDONDA", "SOLEDADE", "TAPEROA", "TENORIO", "UMBUZEIRO",
        "BARAUNA", "BARRA DE SANTA ROSA", "CUITE", "DAMIAO", "FREI MARTINHO", "NOVA FLORESTA", "NOVA PALMEIRA", "PEDRA LAVRADA", "PICUI", "SOSSEGO",
        "CAMALAU", "MONTEIRO", "OURO VELHO", "PRATA", "SAO JOAO DO TIGRE", "SAO SEBASTIAO DO UMBUZEIRO", "ZABELE",
        "AMPARO", "CONGO", "COXIXOLA", "LIVRAMENTO", "PARARI", "SAO JOSE DOS CORDEIROS", "SERRA BRANCA", "SUME"     
    ],
	"PATOS": [
        "AGUA BRANCA", "AREIA DE BARAUNAS", "CACIMBA DE AREIA", "CACIMBAS", "CATINGUEIRA", "COREMAS", "DESTERRO", "EMAS", "IMACULADA", "MAE DAGUA", "MALTA", "MATUREIA", "OLHO DAGUA", "PASSAGEM", "PATOS", "QUIXABA", "SALGADINHO", "SANTA LUZIA", "SANTA TERESINHA", "SAO JOSE DE ESPINHARAS", "SAO JOSE DO BONFIM", "SAO JOSE DO SABUGI", "SAO MAMEDE", "TEIXEIRA", "VARZEA", "VISTA SERRANA",
        "AGUIAR", "BOA VENTURA", "CONCEICAO", "CURRAL VELHO", "DIAMANTE", "IBIARA", "IGARACY", "ITAPORANGA", "NOVA OLINDA", "PEDRA BRANCA", "PIANCO", "SANTA INES", "SANTANA DE MANGUEIRA", "SANTANA DOS GARROTES", "SAO JOSE DE CAIANA",
        "BELEM DO BREJO DO CRUZ", "BOM SUCESSO", "BREJO DO CRUZ", "BREJO DOS SANTOS", "CATOLE DO ROCHA", "JERICO", "MATO GROSSO", "RIACHO DOS CAVALOS", "SAO BENTO", "SAO JOSE DO BREJO DO CRUZ",
        "CAJAZEIRINHAS", "CONDADO", "LAGOA", "PAULISTA", "POMBAL", "SAO BENTINHO", "SAO DOMINGOS",
        "JURU", "MANAIRA", "PRINCESA ISABEL", "SAO JOSE DE PRINCESA", "TAVARES"
    ],
	"SOUSA-CAJAZEIRAS": [
        "APARECIDA", "BERNARDINO BATISTA", "JOCA CLAUDINO", "LASTRO", "MARIZOPOLIS", "NAZAREZINHO", "POCO DANTAS", "SANTA CRUZ", "SAO FRANCISCO", "SAO JOSE DA LAGOA TAPADA", "SOUSA", "UIRAUNA", "VIEIROPOLIS",
        "BOM JESUS", "BONITO DE SANTA FE", "CACHOEIRA DOS INDIOS", "CAJAZEIRAS", "CARRAPATEIRA", "MONTE HOREBE", "POCO DE JOSE DE MOURA", "SANTA HELENA", "SAO JOSE DE PIRANHAS", "SAO JOAO DO RIO DO PEIXE", "SERRA GRANDE", "TRIUNFO"
    ]

}